variables:
    GIT_SUBMODULE_STRATEGY: recursive

cache:
    paths:
        - modules/ommr4all-client/node_modules/

deploy-job:
    stage: deploy
    script:
        - cd modules/ommr4all-client
        - npm install
        - ng build
        - cd ../..

        - virtualenv -p python3 ommr4all-venv
        - source ommr4all-venv/bin/activate
        - pip install -r modules/ommr4all-server/requirements.txt
        - cd modules/page-segmentation && python setup.py install && cd ../..
        - cd modules/ommr4all-line-detection && python setup.py install && cd ../..
        - cd modules/ommr4all-server && python manage.py collectstatic --noinput && cd ../..
        - cd modules/ommr4all-server && sed -i -e 's/ALLOWED_HOSTS = \[\]/ALLOWED_HOSTS = \["*"\]/g' ommr4all/settings.py && cd ../..
        - cd modules/ommr4all-server && sed -i -e 's/DEBUG = True/DEBUG = False/g' ommr4all/settings.py && cd ../..
        - cd modules/ommr4all-server && sed -i -e 's/^SECRET_KEY.*//g' ommr4all/settings.py && echo SECRET_KEY = \'`python manage.py shell -c "from django.core.management import utils; print(utils.get_random_secret_key())"`\' >> ommr4all/settings.py && cd ../..
        - rm -rf /opt/ommr4all/ommr4all-deploy && rm -rf /opt/ommr4all/ommr4all-tmp
        - cp -r $PWD /opt/ommr4all/ommr4all-deploy-tmp && mv /opt/ommr4all/ommr4all-deploy-tmp /opt/ommr4all/ommr4all-deploy


