variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - deploy
  - cleanup

test-server:
  only:
    - master
    - tags
  stage: test
  tags:
    - deployment-production
    - deployment-master
  script:
    - set -e
    - python3 ommr4all-deploy/test.py

deploy-ommr4all-master:
  only:
    - master
  stage: deploy
  tags:
    - deployment-master
  script:
    - set -e
    - python3 ommr4all-deploy/deploy.py

deploy-ommr4all-production:
  only:
    - tags
  stage: deploy
  tags:
    - deployment-production
  script:
    - set -e
    - python3 deploy/deploy.py

cleanup:
  only:
    - master
    - tags
  stage: cleanup
  tags:
    - deployment-production
    - deployment-master
  script:
    - rm -rf *
