variables:
    GIT_SUBMODULE_STRATEGY: recursive

cache:
    paths:
        - modules/ommr4all-client/node_modules/

deploy-job:
    stage: deploy
    script:
        - cd modules/ommr4all-client
        - npm install
        - ng build
        - cd ../..

        - rm -rf /opt/ommr4all/ommr4all-deploy
        - cp -r $PWD /opt/ommr4all/ommr4all-deploy

