variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - deploy
  - cleanup

# dev testing
dev-test:
  only:
    - dev
  stage: test
  tags:
    - deployment-master
  script:
    - set -e
    - python3 ommr4all-deploy/test.py

dev-cleanup:
  only:
    - dev
  stage: cleanup
  tags:
    - deployment-master
  script:
    - rm -rf *

# deploy master
master-test:
  only:
    - master
  stage: test
  tags:
    - deployment-master
  script:
    - set -e
    - python3 ommr4all-deploy/test.py

master-deploy:
  only:
    - master
  stage: deploy
  tags:
    - deployment-master
  script:
    - set -e
    - python3 ommr4all-deploy/deploy.py

master-cleanup:
  only:
    - master
  stage: cleanup
  tags:
    - deployment-master
  script:
    - rm -rf *

# deploy production
production-test:
  only:
    - tags
  stage: test
  tags:
    - deployment-production
  script:
    - set -e
    - python3 ommr4all-deploy/test.py

production-deploy:
  only:
    - tags
  stage: deploy
  tags:
    - deployment-production
  script:
    - set -e
    - python3 ommr4all-deploy/deploy.py

production-cleanup:
  only:
    - tags
  stage: cleanup
  tags:
    - deployment-production
  script:
    - rm -rf *
