variables:
    GIT_SUBMODULE_STRATEGY: recursive

cache:
    paths:
        - modules/ommr4all-client/node_modules/

deploy-job:
    only: master
    stage: deploy
    script:
        - set -e
        - cd modules/ommr4all-client
        - npm install
        - ng build
        - cd ../..

        - virtualenv -p python3 ommr4all-venv
        - source ommr4all-venv/bin/activate
        - pip install -r modules/ommr4all-server/requirements.txt
        - mkdir -p /opt/ommr4all/storage
        - cd modules/page-segmentation && python setup.py install && cd ../..
        - cd modules/ommr4all-line-detection && python setup.py install && cd ../..

        - cd modules/ommr4all-server
        - sed -i -e 's/ALLOWED_HOSTS = \[\]/ALLOWED_HOSTS = \["*"\]/g' ommr4all/settings.py
        - sed -i -e 's/DEBUG = True/DEBUG = False/g' ommr4all/settings.py
        - sed -i -e 's#db.sqlite3#/opt/ommr4all/db.sqlite3#g' ommr4all/settings.py
        - sed -i -e "s#BASE_DIR, 'storage'#'/opt/ommr4all/storage'#g" ommr4all/settings.py
        - python manage.py collectstatic --noinput
        - python manage.py migrate
        - echo SECRET_KEY = \'`python manage.py shell -c "from django.core.management import utils; print(utils.get_random_secret_key())"`\' > ommr4all/settings_new.py && sed -i -e 's/^SECRET_KEY.*//g' ommr4all/settings.py && cat ommr4all/settings.py >> ommr4all/settings_new.py && rm ommr4all/settings.py && mv ommr4all/settings_new.py ommr4all/settings.py
        - cd ../..

        - rm -rf /opt/ommr4all/ommr4all-deploy && rm -rf /opt/ommr4all/ommr4all-tmp
        - cp -r $PWD /opt/ommr4all/ommr4all-deploy-tmp && mv /opt/ommr4all/ommr4all-deploy-tmp /opt/ommr4all/ommr4all-deploy


