variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

deploy-job:
    stage: deploy
    script:
        - cd modules/ommr4all-client && npm install
        - cd modules/ommr4all-client && ng build
